### ISSUE TITLE
Refresh the Windows Store icon

### ISSUE THREAD

**Issue by moeenio** [B00merang-Artwork/Windows-10#22]
The Windows store icon (used here for package management) is out-of-date, windows now has [this](https://cdn.wccftech.com/wp-content/uploads/2017/10/microsoft-store-icon.jpg) since a bit of time.

**Comment by Elbullazul** [comment]
I'm going to close this one and post updates on the [previously opened issue](https://github.com/B00merang-Artwork/Windows-10/issues/11)
