### ISSUE TITLE
Missing License?

### ISSUE THREAD

**Issue by flozz** [B00merang-Artwork/Windows-10#26]
Hello,

I have few questions about the license of this projet:

* What is the license of this icon theme?
* Are we allowed to redistribute it along an other software?
* Is it possible to add a license file to this repository?

**Comment by Elbullazul** [comment]
Hi,

This icon theme was uploaded by someone without a license, and they disappeared not long afterwards.

I say use it as you wish, but I can't guarantee the source is GPL compliant

**Comment by flozz** [comment]
Argh so sad... 

Thank you for the answer! :)

**Comment by mibmo** [comment]
Seems they're licensed as GPL3. See https://b00merang.weebly.com/licensing.html :)

EDIT: in hindsight, of course they're owned by Microsoft (or related) and therefore not GPL compliant nor "free to use".

**Comment by hirntot** [comment]
> This icon theme was uploaded by someone without a license

but you are sure, they are not original windows icons and therefore copyrighted by them?

**Comment by Elbullazul** [comment]
@hirntot I don't know. If it turns out they are, I'll remove them when requested to do so.
