### ISSUE TITLE
Remove ( X ) icon is used instead of decrement ( - )

### ISSUE THREAD

**Issue by wojciechrak** [B00merang-Artwork/Windows-10#4]
In many places a remove (red X) icon is used, where there should be a minus sign. Especially on number input fields like in LibreOffice Writer:

![obraz](https://user-images.githubusercontent.com/3034230/35828872-638be4e4-0ac1-11e8-9c2e-b2ef13ff0df1.png)

Humanity icon set, for reference:
![obraz](https://user-images.githubusercontent.com/3034230/35828931-9379010a-0ac1-11e8-8d79-757090a6d7f2.png)

**Comment by Elbullazul** [comment]
fixed
