### ISSUE TITLE
gnome-system-monitor icon is no longer being modified.

### ISSUE THREAD

**Issue by Zerophase** [B00merang-Artwork/Windows-10#6]
I believe this has been an issue since gnome 3.28. Remains as the default Gnome system monitor icon. All of the other themes I have checked (arc, adwaita, and numix) seem to have this issue as well.  Have any idea what is going on?

**Comment by Elbullazul** [comment]
I don't know, but I'll have a look at it later. Maybe it's because it's a snap app now?

**Comment by feren** [comment]
org.gnome.Monitor, or something like that?

**Comment by Elbullazul** [comment]
snap apps apparently have no support for external icon theming.

from ubuntu budgie forums: https://discourse.ubuntubudgie.org/t/apply-icon-theme-to-snap-packages/951/4

**Comment by Elbullazul** [comment]
also, yes. the icon name is gnome-system-monitor

**Comment by Zerophase** [comment]
One of the icons is just missing. I fixed it on my local machine. Do you still need the fix?

**Comment by Elbullazul** [comment]
Yes, can you submit a PR?
