### ISSUE TITLE
[request] symbolic icons for xfce 'show desktop' and side pane of thunar file manager

### ISSUE THREAD

**Issue by denikris** [B00merang-Artwork/Windows-10#7]
papirus dark and windows 10 icon side by side
![symbolic](https://user-images.githubusercontent.com/16707606/52158534-c2cde200-26cb-11e9-9ba8-e0a5e38ad85e.png)

**Comment by Elbullazul** [comment]
I can setup a branch with that mod, but probably won't be pushed to master, since it's not how Windows 10 looks:

![image](https://user-images.githubusercontent.com/15310985/52170649-60510200-271c-11e9-9804-03c25a0ac6fd.png)

However, the house icon looks out of place, so I'll work on that.

**Comment by denikris** [comment]
you're right, maybe **show desktop** icon on the xfce panel (image right) that only need change
